In [1]:
# recall from last ex:
import pandas as pd
url = 'https://raw.githubusercontent.com/ShaiYona/Data-Science2021B/main/tirgulim/tirgul1/titanic_short.csv'
data = pd.read_csv(url)
data.head()

pclass  survived      age     sex
0    1st         1  29.0000  female
1    1st         0   2.0000  female
2    1st         0  30.0000    male
3    1st         0  25.0000  female
4    1st         1   0.9167    male

In [3]:
short_data = data[0:3]
short_data

pclass  survived   age     sex
0    1st         1  29.0  female
1    1st         0   2.0  female
2    1st         0  30.0    male

In [4]:
short_data[[True,False,True]]

pclass  survived   age     sex
0    1st         1  29.0  female
2    1st         0  30.0    male

In [5]:
# what will be the result of the following code? why?
# short_data[[False,True]]

ValueError: ignored

In [ ]:
# display rows 10-18
data[10:19]

pclass  survived   age     sex
10    1st         0  47.0    male
11    1st         1  19.0  female
12    1st         1   NaN  female
13    1st         1   NaN    male
14    1st         0   NaN    male
15    1st         1  50.0  female
16    1st         0  24.0    male
17    1st         0  36.0    male
18    1st         1  37.0    male

In [ ]:
# not null
filteredData = data[pd.notnull(data['age'])]
filteredData[10:19]

pclass  survived   age     sex
10    1st         0  47.0    male
11    1st         1  19.0  female
15    1st         1  50.0  female
16    1st         0  24.0    male
17    1st         0  36.0    male
18    1st         1  37.0    male
20    1st         1  26.0    male
21    1st         0  25.0    male
23    1st         1  19.0  female

In [ ]:
# Mean
dataAge = data['age']
dataAge.mean()


34.90942173913044

In [ ]:
dataAge.min()

0.9167

In [ ]:
dataAge.max()

71.0

In [ ]:
dataAge.median()

30.0

## Numpy
Matrices and much more, this is where the fun begins..

[Numpy official docs](https://numpy.org/doc/stable/reference/index.html)

In [ ]:
import numpy as np
# create ones matrix of specific size:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# self excercise: create zeros matrix of specific size:






In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# The I matrix
d = np.eye(3)
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# self excercise: create the following 3X3 diagonal matrix
[1., 0., 0.],
[0., 2., 0.],
[0., 0., 3.]









[0.0, 0.0, 3.0]

In [ ]:
[1,2,3]*np.eye(3)

array([[1., 0., 0.],
       [0., 2., 0.],
       [0., 0., 3.]])

In [ ]:
# random
e = np.random.random((2,4)) 
print(e)

[[0.18376809 0.77458134 0.56778592 0.56931201]
 [0.90032788 0.73304361 0.32810382 0.01482418]]


In [ ]:
# append
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([11, 12, 13, 14, 15])
arr3 = np.append(arr1,arr2)
print(arr3)


[ 1  2  3  4  5 11 12 13 14 15]


In [ ]:
# we can add arrays of same length
print(arr1+arr2)

[12 14 16 18 20]


In [ ]:
# However arrays must have same length
arr3 = np.array([1,2])
# print(arr1+arr3) # ERROR

In [ ]:
# self excercise: Assume hypothethical case where you wish for each student to calculate average of the highest 5 grades out of 6 student's assignment
# step 1. generate 10X6 random integer numbers between 70 to 100 to represent students grades
# step 2. calculate mean of top 5 grades for each student








In [ ]:
numCols = 6
grades = np.random.randint(70,100,size=(10,numCols))
print(grades)

[[80 76 73 71 91 73]
 [91 99 79 74 96 92]
 [81 94 99 78 86 78]
 [87 85 80 70 91 71]
 [90 79 71 86 71 72]
 [75 79 78 96 99 92]
 [81 94 77 93 83 80]
 [92 88 88 81 72 90]
 [92 70 80 97 75 95]
 [77 70 94 90 78 92]]


In [ ]:
top5Avg = (grades.sum(axis=1)-grades.min(axis=1)) / (numCols-1)
top5Avg = top5Avg.reshape(len(top5Avg),1) #set as column instead of a row
print(top5Avg)

[[78.6]
 [91.4]
 [87.6]
 [82.8]
 [79.6]
 [88.8]
 [86.2]
 [87.8]
 [87.8]
 [86.2]]


In [ ]:
# create array in specific range
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(10,14)

array([10, 11, 12, 13])

In [ ]:
np.arange(10,20,2) # note 20 not included

array([10, 12, 14, 16, 18])

In [ ]:
np.arange(20,10,-2)

array([20, 18, 16, 14, 12])

In [ ]:
filteredData.head(10)

pclass  survived      age     sex
0    1st         1  29.0000  female
1    1st         0   2.0000  female
2    1st         0  30.0000    male
3    1st         0  25.0000  female
4    1st         1   0.9167    male
5    1st         1  47.0000    male
6    1st         1  63.0000  female
7    1st         0  39.0000    male
8    1st         1  58.0000  female
9    1st         0  71.0000    male

In [ ]:
filteredAge = filteredData[['age']] # this is a dataframe with headers and indices (note the [[]])
type(filteredAge)

pandas.core.frame.DataFrame

In [ ]:
filteredAge.head()

age
0  29.0000
1   2.0000
2  30.0000
3  25.0000
4   0.9167

In [ ]:
filteredAge = filteredData['age'] # this is a series without headers and indices (note the [)
type(filteredAge)

pandas.core.series.Series

In [ ]:
filteredAge

0     29.0000
1      2.0000
2     30.0000
3     25.0000
4      0.9167
5     47.0000
6     63.0000
7     39.0000
8     58.0000
9     71.0000
10    47.0000
11    19.0000
15    50.0000
16    24.0000
17    36.0000
18    37.0000
20    26.0000
21    25.0000
23    19.0000
24    28.0000
26    39.0000
27    30.0000
28    58.0000
Name: age, dtype: float64

In [ ]:
# ages = filteredData['age']
# ages.to_numpy()

array([29.    ,  2.    , 30.    , 25.    ,  0.9167, 47.    , 63.    ,
       39.    , 58.    , 71.    , 47.    , 19.    , 50.    , 24.    ,
       36.    , 37.    , 26.    , 25.    , 19.    , 28.    , 39.    ,
       30.    , 58.    ])

## self learning:
### 1. read tutorial 4
### 2. View tutorials from the following source (as much as you can):
[Python Pandas Tutorials](https://www.youtube.com/watch?v=ZyhVh-qRZPA&list=PL-osiE80TeTsWmV9i9c58mdDCSskIFdDS) 

In [ ]:

x

NameError: name 'x' is not defined